### ISSUE TITLE
No module named icaro.hardware.icaro.modulos

### ISSUE THREAD

**Issue by searchsam** [fitoria/icaro-cli#1]
Error when trying to compile and load a code on my board NP_08
Traceback (most recent call last):
  File "/bin/icaro-cli", line 9, in <module>
    load_entry_point('icaro-cli==0.1', 'console_scripts', 'icaro-cli')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2386, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python2.7/site-packages/icaro_cli-0.1-py2.7.egg/icaro_cli/**init**.py", line 17, in <module>
    from icaro.hardware.icaro.modulos import docker
ImportError: No module named icaro.hardware.icaro.modulos

**Comment by fitoria** [comment]
Se necesita tener instalado icaro desde el paquete de fedora para que icaro-cli funcione 

probá que esta instalado haciendo lo siguiente en  una consola de python

> > > import icaro

Y si eso no da error es que está instalado.

Saludos

**Comment by searchsam** [comment]
Ahhhh, ok, tengo el icaro que tengo instalado es el de repo icaro-spec de Valentin.
